invoicing/urls.py
"""Invoicing URLs."""

#Django
from django.urls import path

#views

from invoicing import views

urlpatterns = [

	path(
		route='', 
		view=views.dashboard,
		name='dashboard'
	),
	path(
		route='create_company/', 
		view=views.CreateCompanyView.as_view(),
		name='create_company'
	),
	path(
    	route='company/', 
    	view=views.ListCompanyView.as_view(), 
    	name='companies'
    ),


    path(
    	route='create_product/', 
    	view=views.CreateProductView.as_view(), 
    	name='create_product'
    ),
    path(
    	route='products/', 
    	view=views.ListProductsView.as_view(), 
    	name='products'
    ),

]

kaumerito/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
	path('admin/', admin.site.urls),

	path('', include(('invoicing.urls','invoicing'), namespace='invoicing')),
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoicing/models.py
from django.db import models

# Create your models here.
class Company(models.Model):
	"""Company Data"""

	company_name = models.CharField(max_length=55)
	address = models.CharField(max_length=255, blank=True)
	phone_number = models.CharField(max_length=20, blank=True)
	city = models.CharField(max_length=255, blank=True)
	state = models.CharField(max_length=255, blank=True)
	country = models.CharField(max_length=255, blank=True)

	def __str__(self):
		return self.company_name

class Products(models.Model):
	"""Products of the Company"""

	company = models.ForeignKey(Company, on_delete=models.CASCADE)

	product_name = models.CharField(max_length=55)
	sales_price = models.CharField(max_length=55)
	buy_price = models.CharField(max_length=55)

	def __str__(self):
		"""Return name."""
		return self.product_name

invoicing/forms.py
"""Invoicing Forms"""

#Django
from django import forms

#Models
from invoicing.models import Company, Products

class CompanyForm(forms.ModelForm):

	class Meta:

		model = Company
		fields = ('company_name', 
			'address', 
			'phone_number', 
			'city',
			'state',
			'country',
		)

class ProductForm(forms.ModelForm):

	class Meta:

		company = forms.ModelChoiceField(queryset=Company.objects.filter(id=1))
		model = Products
		fields = ('company', 
			'product_name', 
			'sales_price', 
			'buy_price',
		)

invoicing/views.py
#Django
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView
from django.urls import reverse_lazy

from django.http import HttpResponse

# Forms
from invoicing.forms import CompanyForm, ProductForm

#Models
from invoicing.models import Company, Products

def dashboard(request):
	return render(request, 'invoicing/dashboard.html')


class CreateCompanyView(CreateView):

	template_name = 'invoicing/create_company.html'
	form_class = CompanyForm
	success_url = reverse_lazy('invoicing:dashboard')

class ListCompanyView(ListView):

    template_name = 'invoicing/list_company.html'
    model = Company
    ordering = ('company_name',)
    paginate_by = 30
    context_object_name = 'companies'

class CreateProductView(CreateView):

	template_name = 'invoicing/create_product.html'
	form_class = ProductForm
	success_url = reverse_lazy('invoicing:products')

class ListProductsView(ListView):

    template_name = 'invoicing/list_products.html'
    model = Products
    ordering = ('product_name',)
    paginate_by = 30
    context_object_name = 'products'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/sb-admin.css' %}" />
  

</head>
<body>

    {% include "nav.html" %}


<div id="wrapper">

    <!-- Sidebar -->
    
    {% include "sidebar.html" %}

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol>
        {% block container %}{% endblock%}
        
        

      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Your Website 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>



      <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{% static 'vendor/chart.js/Chart.min.js"></script>
  <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin.min.js' %}"></script>

  <!-- Demo scripts for this page-->
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>

</body>
</html>

templates/invoicing/create_company.html
{% extends "base.html" %}

{% block head_content %}
    <title>Crear Empresa</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Crea Empresa!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {# company_name field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.company_name.errors %}is-invalid{% endif %}"
                            type="text"
                            name="company_name"
                            placeholder="Nombre de la empresa"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.company_name.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# address field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.address.errors %}is-invalid{% endif %}"
                            type="text"
                            name="address"
                            placeholder="Dirección de la empresa"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.address.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# phone_number field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                            type="text"
                            name="phone_number"
                            placeholder="Teléfono"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.phone_number.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# city field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.city.errors %}is-invalid{% endif %}"
                            type="text"
                            name="city"
                            placeholder="Ciudad"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.city.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# state field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.state.errors %}is-invalid{% endif %}"
                            type="text"
                            name="state"
                            placeholder="Departamente/Estado"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.state.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# pais field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.pais.errors %}is-invalid{% endif %}"
                            type="text"
                            name="pais"
                            placeholder="Pais"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.pais.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>


                    <button type="submit" class="btn btn-primary btn-block mt-5">Crear!</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/invoicing/create_product.html
{% extends "base.html" %}

{% block head_content %}
    <title>Crear Producto</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Crear Producto!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {# product_name field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.product_name.errors %}is-invalid{% endif %}"
                            type="text"
                            name="product_name"
                            placeholder="Nombre del producto"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.product_name.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# sales_price field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.sales_price.errors %}is-invalid{% endif %}"
                            type="text"
                            name="sales_price"
                            placeholder="Precio de venta"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.sales_price.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# buy_price field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.buy_price.errors %}is-invalid{% endif %}"
                            type="text"
                            name="buy_price"
                            placeholder="Precio de compra"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.buy_price.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# company field #}
                    <div class="form-group">
                        <select
                            class="form-control {% if form.company.errors %}is-invalid{% endif %}"
                            type="text"
                            name="company"
                            placeholder="Empresa al que pertenece"
                        >
                            <option value="1">Elversote</option>
                        </select>
                    </div>

                    


                    <button type="submit" class="btn btn-primary btn-block mt-5">Crear!</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/invoicing/dashboard.html
{% extends "base.html" %}

{% block head_content %}
    <title>Kaumerito App</title>
{% endblock%}

{% block container %}
	<!-- Icon Cards-->
        <div class="row">
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-comments"></i>
                </div>
                <div class="mr-5">News!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-list"></i>
                </div>
                <div class="mr-5">11 New Tasks!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-shopping-cart"></i>
                </div>
                <div class="mr-5">123 New Orders!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-life-ring"></i>
                </div>
                <div class="mr-5">13 New Tickets!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
        </div>

        <!-- Area Chart Example-->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-chart-area"></i>
            Exprésate</div>
          <div class="mr-5"></div>
          <div class="container">
        <div class="row">

            <p>Hello World!</p>
        </div>
          <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>

    
    </div>
{% endblock %}

templates/invoicing/list_company.html
{% extends "base.html" %}

{% block head_content %}
    <title>Mi Empresa</title>
{% endblock%}

{% block container %}
    <div class="container">
     
                    <!-- DataTables Example -->
                <div class="card mb-3">
                  <div class="card-header">
                    <i class="fas fa-table"></i>
                    Empresas</div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>

                          <tr>
                            <th>Nombre</th>
                            <th>Dirección</th>
                            <th>Teléfono</th>
                            <th>Ciudad</th>
                            <th>Estado</th>
                            <th>Pais</th>
                            <th>Acción</th>
                          </tr>
                        
                        </thead>
                        <tfoot>
                          <tr>
                            <th>Nombre</th>
                            <th>Dirección</th>
                            <th>Teléfono</th>
                            <th>Ciudad</th>
                            <th>Estado</th>
                            <th>Pais</th>
                            <th>Acción</th>
                          </tr>
                        </tfoot>
                        <tbody>
                        {% for company in companies %}
                          <tr>
                            <td>{{ company.company_name }}</td>
                            <td>{{ company.address }}</td>
                            <td>{{ company.phone_number }}</td>
                            <td>{{ company.city }}</td>
                            <td>{{ company.state }}</td>
                            <td>{{ company.country }}</td>
                            <td>{{ company.country }}</td>
                          </tr>
                        {% endfor %}
        
                          
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                </div>
            

    </div>
{% endblock %}

templates/invoicing/list_products.html
{% extends "base.html" %}

{% block head_content %}
    <title>Mi Empresa</title>
{% endblock%}

{% block container %}
    <div class="container">
     
                    <!-- DataTables Example -->
                <div class="card mb-3">
                  <div class="card-header">
                    <i class="fas fa-table"></i>
                    Productos</div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>

                          <tr>
                            
                            <th>Nombre Producto</th>
                            <th>Precio Venta</th>
                            <th>Precio Compra</th>
                            <th>Acción</th>
                          </tr>
                        
                        </thead>
                        <tfoot>
                          <tr>
                            
                            <th>Nombre Producto</th>
                            <th>Precio Venta</th>
                            <th>Precio Compra</th>
                            <th>Acción</th>
                          </tr>
                        </tfoot>
                        <tbody>
                        {% for product in products %}
                          <tr>
                            
                            <td>{{ product.product_name }}</td>
                            <td>{{ product.sales_price }}</td>
                            <td>{{ product.buy_price }}</td>
                            <td>Acción</td>
                          </tr>
                        {% endfor %}
        
                          
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                </div>
            

    </div>
{% endblock %}

templates/nav.html
{% load static %}

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">Kaumerito</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{% url "invoicing:create_company" %}">Nueva Empresa</a>
          <a class="dropdown-item" href="{% url "invoicing:companies" %}">Empresa</a>
        </div>
      </li>
    </ul>

  </nav>

templates/sidebar.html
{% load static %}

<ul class="sidebar navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "invoicing:dashboard" %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Invoicing</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Facturación:</h6>
          <a class="dropdown-item" href="">Nueva Factura</a>
          <a class="dropdown-item" href="">Ver Facturas</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Products</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Productos:</h6>
          <a class="dropdown-item" href="{% url "invoicing:create_product" %}">Nuevo Producto</a>
          <a class="dropdown-item" href="{% url "invoicing:products" %}">Ver Productos</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>
    </ul>